### PR TITLE
Plugin triggers

### PR DESCRIPTION
**Pull request by josephduchesne**
Added a fairly generic system for plugins to tell eachother when various trigger events occur

Example use case:
- A collision detector plugin can trigger the tween plugin to change state
- Triggering automatic sliding doors
- Triggering an annoying "person" to walk out just as the robot approaches

### CODE REVIEW

**Comment by lichunshang** [comment]
I am not entirely sure why internal triggers are necessary, plugins can simply subscribe to the corresponding messages other plugins outputs?

**Comment by josephduchesne** [comment]
This allows easily triggering plugins attached to specific things. The simplest is triggering things on the same item. I developed it to try to reduce the complexity of the Tween plugin. I would like to use it in a variety of scenarios (sliding doors, moving obstacles, etc.) but don't really want to but N different mechanisms for triggering it to start/stop moving. This way any other plugin can trigger other plugins attached to a model without worrying about publishers, subscribers, or topic names.

**Comment by lichunshang** [comment]
People, automatic doors etc would be a different model with its own plugins, but the trigger only works within the same model? Also, shouldn't people and doors detect the presence of robot/objects themselves, rather than the robot firing events to command the people/doors? Like automatic doors could simply detect bodies in its proximity?

**Comment by josephduchesne** [comment]
The idea is that with a few plugins that trigger action, and a few plugins that perform actions, you could create a wide variety of different objects, while keeping the number, complexity, and specificity of the plugins down. It might be better to use rostopic for this. We can discuss Monday.

An example would be a person walking triggered by another object hitting the object's sensor might have one sensor plugin that triggers object to start moving, and another closer sensor plugin that triggers the object to stop, and a tween plugin to handle the motion itself. Thus you get the fairly complex behavior of a person walking out into the path of the robot, but not walking into it with two relatively simple plugins.

**Comment by lichunshang** [comment]
Or we can make this exist as two plugins. One tweeny plugin that just does the tween stuff on a body. And a tween trigger plugin that checks for the various conditions, like a different plugin for sensor collision, timed, or what ever the way to trigger it. Then the tween plugin just offers a service to perform the tweening?

**Comment by josephduchesne** [comment]
Closing in favour of a different solution

**Pull request closed without merging**
