### PR TITLE
Ros2 plugins port

### PR DESCRIPTION
**Pull request by josephduchesne**
I'm opening this as a placeholder for the branch (now misnamed for the most part) that Nico's changes merged into.

### CODE REVIEW

**Comment by mbuijs** [comment]
May I ask what is the state of this PR?

**Comment by josephduchesne** [comment]
Hi @mbuijs , this port is mostly working. 
Summary:
- Flatland Viz is still not 100%
- the simulator and plugins should all work.
- Unit tests are broken since  they're currently trying to build for ros1. The travisci config needs updating to point to ros2 in this branch.

**Comment by BerserkingIdiot** [comment]
Are there plans to continue the ROS2 port, or has it been effectively become abandoned/stale?

**Comment by josephduchesne** [comment]
> Are there plans to continue the ROS2 port, or has it effectively become abandoned/stale?

I would like to continue the ROS2 port, as well as firm up the build system and get packages into the ROS mainline repos.

We've been using Flatland regularly on ROS1 at Avidbots (and continue to do so), but ROS2 support hasn't really become a major priority for us. As a result, this effort is more of a hobby/personal project for the time being, but if you're interested I may resume work on it soon. I wouldn't mind having ROS1 and ROS2 distributions in place for ROSCON this year (October).

**Comment by BerserkingIdiot** [comment]
> > Are there plans to continue the ROS2 port, or has it effectively become abandoned/stale?
> 
> I would like to continue the ROS2 port, as well as firm up the build system and get packages into the ROS mainline repos.
> 
> We've been using Flatland regularly on ROS1 at Avidbots (and continue to do so), but ROS2 support hasn't really become a major priority for us. As a result, this effort is more of a hobby/personal project for the time being, but if you're interested I may resume work on it soon. I wouldn't mind having ROS1 and ROS2 distributions in place for ROSCON this year (October).

Thank you for the positive response! We're currently considering using Flatland on robotics courses at FEUP, so we're very much interested in the development of the ROS2 port.

**Pull request closed without merging**
