### PR TITLE
New service to move a model to specified global pose

### PR DESCRIPTION
**Pull request by robustify**
Hello!  I listened to your lightning talk at ROSCON and decided to check out your cool simulator.  I was intrigued because I teach an introductory robotics course at my alma mater, and was thinking of ways my students could make meaningful simulations that didn't involve Gazebo, since some of them tend to have weaker laptops or are running VMs.

As a way to introduce myself to flatland and you guys, I created this hopefully useful MoveModel service and integrated it into the existing ServiceManager class.  I envision using it to reset simulation scenarios without having to bring down the whole simulator.

I also think it would be cool to create interactive markers to manipulate the models directly in the Rviz viewer and update the model poses with the MoveModel service when you let go of the interactive markers.  I'll poke around with this and make a pull request if the efforts are fruitful, and if you're interested.

Let me know what you think!

### CODE REVIEW

**Comment by josephduchesne** [comment]
One other suggestion would be to add a brief description of the service to the flatland ros service documentation section in this file:

docs/core_functions/ros_services.rst

This ends up here: http://flatland-simulator.readthedocs.io/en/latest/core_functions/ros_services.html

**Comment by robustify** [comment]
I noticed the crazy number of commits right after submitting the pull request!  I just deleted my fork, re-forked the main repository, and reapplied my changes manually.

It doesn't look like I can update this pull request to be from my new fork, as it says it's coming from an "unknown repository", so I'm closing this one and creating a new one.

**Comment by josephduchesne** [comment]
Sorry about the mess. Hopefully nobody else gets caught in this!

**Comment by mbrousse** [comment]
MoveModel is a great idea, but I think a more powerful way to position more than one model at a time would also be useful. A way to position multiple models in:

a row 1d
rows and columns 2d
along a curve
random distribution

Use cases: 
auditorium filled with chairs
randomly placed plants
position obstacles wrt robot

**Comment by josephduchesne** [comment]
I've written a spec for world plug-ins (like model plug-ins but attached to the world). They might be suitable for mass spawning or moving models like that. It should hit master in a few days. The in house use case is perturbing the walls to simulate a changed environment but I want to write a maze generator as well.

**Comment by mbrousse** [comment]
Happy to see Flatland project is gaining momentum and talent. We might think about other kinds of mass model behavior in addition to spawning, such as would be more applicable for the update rather than the init. 

For example:
swarming/ coordinated behaviour
people entering/leaving in a queue
people standing around chatting (idle animation + AI gathering)
movement of skids, trolleys, trailers, forklifts, shopping carts and of course other floor cleaners driven only by a human.
blind person with luggage
zombies
bake changing lighting

**Pull request closed without merging**
